at AfterCode<_, _>, after F# inits the sm, and we can attach extra info
MoveNextAsync...
at MoveNextAsync: normal resumption scenario
at MoveNextAsync: start calling builder.MoveNext()
Resuming at resumption point 0
at Run.MoveNext start
at Bind
at Bind: with __stack_fin = false
at Bind: calling AwaitUnsafeOnCompleted
at Run.MoveNext, __stack_code_fin=False
at Run.MoveNext, await
at MoveNextAsync: done calling builder.MoveNext()
at MoveNextAsyncResult: case pending/faulted/cancelled...
at Bind: with __stack_fin = true
at Bind: with getting result from awaiter
at Bind: calling continuation
at Bind
at Bind: with __stack_fin = false
at Bind: calling AwaitUnsafeOnCompleted
at Run.MoveNext, __stack_code_fin=False
at Run.MoveNext, await
at Bind: with __stack_fin = true
at Bind: with getting result from awaiter
at Bind: calling continuation
at Bind
at Bind: with __stack_fin = false
at Bind: calling AwaitUnsafeOnCompleted
at Run.MoveNext, __stack_code_fin=False
at Run.MoveNext, await
at Bind: with __stack_fin = true
at Bind: with getting result from awaiter
at Bind: calling continuation
at Zero()
at Run.MoveNext, __stack_code_fin=True
at Run.MoveNext, done
Getting result for token on 'None' branch, status: Succeeded
GetAsyncEnumerator, cloning...
MoveNextAsync...
at MoveNextAsync: normal resumption scenario
at MoveNextAsync: start calling builder.MoveNext()
at Bind: with __stack_fin = true
at Bind: with getting result from awaiter
Setting exception of PromiseOfValueOrEnd to: Object reference not set to an instance of an object.
at MoveNextAsync: done calling builder.MoveNext()
at MoveNextAsyncResult: case pending/faulted/cancelled...
Getting result for token on 'None' branch, status: Faulted
Error 'Object reference not set to an instance of an object.' for token: 2
DisposeAsync...
DisposeAsync...
Setting exception of PromiseOfValueOrEnd to: An attempt was made to transition a task to a final state when it had already completed.
System.NullReferenceException: Object reference not set to an instance of an object.
   at FSharpy.Tests.Bug #42 -- synchronous.CE empty taskSeq\, GetAsyncEnumerator - MoveNextAsync multiple times@54.MoveNext() in D:\Projects\OpenSource\Abel\TaskSeq\src\FSharpy.TaskSeq.Test\TaskSeq.StateTransitionBug.Tests.CE.fs:line 62
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90